// basic/react-host/src/App.tsx
import React, { useRef, useEffect } from "react";
import ReactDOM from "react-dom";

import CounterWrapper from "remote/CounterWrapper";

import "./index.css";

const App = () => {
  const divRef = useRef(null);

  useEffect(() => {
    CounterWrapper(divRef.current);
  }, []);
  return (
    <div className="container">
      <div>Name: react-host</div>
      <div ref={divRef}>Framework: react</div>
    </div>
  );
};
ReactDOM.render(<App />, document.getElementById("app"));

// music-shop/music-shop-purchase/src/App.tsx
import { render } from "solid-js/web";

import "./index.css";

const App = () => (
  <div class="container">
    <div>Name: music-shop-purchase</div>
    <div>Framework: solid-js</div>
    <div>Language: TypeScript</div>
    <div>CSS: Empty CSS</div>
  </div>
);
render(App, document.getElementById("app"));
