// music-shop/music-shop-purchase/src/App.tsx
import { render } from "solid-js/web";

import "./index.css";

const App = () => (
  <div class="container">
    <div>Name: music-shop-purchase</div>
    <div>Framework: solid-js</div>
    <div>Language: TypeScript</div>
    <div>CSS: Empty CSS</div>
  </div>
);
render(App, document.getElementById("app"));

// music-shop/music-shop-home/src/App.tsx
import React from "react";
import ReactDOM from "react-dom";

import "./index.css";

const App = () => (
  <div className="container">
    <div>Name: music-shop-home</div>
    <div>Framework: react</div>
    <div>Language: TypeScript</div>
    <div>CSS: Empty CSS</div>
  </div>
);
ReactDOM.render(<App />, document.getElementById("app"));
